version: '3.8'
services:
  db-minerva:
    container_name: postgres-rasa
    image: postgres:16.2
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rasa
    volumes:
      - ./docker/postgres/data_rasa:/var/lib/postgresql/data
      - ./sql/docker:/scripts
    ports:
      - "127.0.0.1:5435:5432"
    command:
      - "postgres"
      - "-c"
      - "timezone=America/El_Salvador"